// api/quote.js
export default function handler(req, res) {
    const quotes = [
      { quote: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
      { quote: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
      { quote: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
      { quote: "If you are working on something exciting, it will keep you motivated.", author: "Unknown" },
      { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
      { quote: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
      { quote: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
      { quote: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
      { quote: "The harder the battle, the sweeter the victory.", author: "Les Brown" },
      { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
      { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
      { quote: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
      { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
      { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
      { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
      { quote: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
      { quote: "Don't limit your challenges. Challenge your limits.", author: "Unknown" },
      { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
      { quote: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
      { quote: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
      { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
      { quote: "Do what you love and success will follow.", author: "Unknown" },
      { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
      { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
      { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
      { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
      { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
      { quote: "Don't wait for opportunity. Create it.", author: "Unknown" },
      { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
      { quote: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
      { quote: "Everything you want is out there waiting for you to ask.", author: "Jack Canfield" },
      { quote: "If you can dream it, you can do it.", author: "Walt Disney" },
      { quote: "Great things never come from comfort zones.", author: "Unknown" },
      { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
      { quote: "Sometimes later becomes never. Do it now.", author: "Unknown" },
      { quote: "Magic is believing in yourself. If you can make that happen, you can make anything happen.", author: "Johann Wolfgang von Goethe" },
      { quote: "Success is the sum of small efforts, repeated day-in and day-out.", author: "Robert Collier" },
      { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
      { quote: "Creativity is intelligence having fun.", author: "Albert Einstein" },
      { quote: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
      { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
      { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
      { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
      { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
      { quote: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
      { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
      { quote: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
      { quote: "Do not wait to strike till the iron is hot; but make it hot by striking.", author: "William Butler Yeats" },
      { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
      { quote: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
      { quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
      { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
      { quote: "Keep going. Be all in.", author: "Bryan Hutchinson" }
    ];
  
    const randomIndex = Math.floor(Math.random() * quotes.length);
    res.status(200).json(quotes[randomIndex]);
  }
  