// api/quote.js
export default function handler(req, res) {
  const quotes = [
    { id: 1,  quote: "The best way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { id: 2,  quote: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
    { id: 3,  quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    { id: 4,  quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { id: 5,  quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
    { id: 6,  quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { id: 7,  quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { id: 8,  quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { id: 9,  quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    { id: 10, quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { id: 11, quote: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
    { id: 12, quote: "Hard work beats talent when talent doesn’t work hard.", author: "Tim Notke" },
    { id: 13, quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { id: 14, quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    { id: 15, quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { id: 16, quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { id: 17, quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { id: 18, quote: "Great things never come from comfort zones.", author: "Unknown" },
    { id: 19, quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    { id: 20, quote: "Sometimes later becomes never. Do it now.", author: "Unknown" },
    { id: 21, quote: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
    { id: 22, quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { id: 23, quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    { id: 24, quote: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
    { id: 25, quote: "Don’t wait for opportunity. Create it.", author: "Unknown" },
    { id: 26, quote: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { id: 27, quote: "Do what you can with all you have, wherever you are.", author: "Theodore Roosevelt" },
    { id: 28, quote: "Creativity is intelligence having fun.", author: "Albert Einstein" },
    { id: 29, quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { id: 30, quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { id: 31, quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    { id: 32, quote: "Motivation gets you started. Habit keeps you going.", author: "Jim Ryun" },
    { id: 33, quote: "Make each day your masterpiece.", author: "John Wooden" },
    { id: 34, quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
    { id: 35, quote: "If you can dream it, you can do it.", author: "Walt Disney" },
    { id: 36, quote: "Small daily improvements lead to stunning results.", author: "Robin Sharma" },
    { id: 37, quote: "Fall seven times and stand up eight.", author: "Japanese Proverb" },
    { id: 38, quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
    { id: 39, quote: "Do what you love and success will follow.", author: "Unknown" },
    { id: 40, quote: "If opportunity doesn’t knock, build a door.", author: "Milton Berle" },
    { id: 41, quote: "Perseverance is not a long race; it is many short races one after another.", author: "Walter Elliot" },
    { id: 42, quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant" },
    { id: 43, quote: "The expert in anything was once a beginner.", author: "Helen Hayes" },
    { id: 44, quote: "Dream it. Wish it. Do it.", author: "Unknown" },
    { id: 45, quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
    { id: 46, quote: "Well done is better than well said.", author: "Benjamin Franklin" },
    { id: 47, quote: "Quality is not an act, it is a habit.", author: "Aristotle" },
    { id: 48, quote: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
    { id: 49, quote: "Make it simple. Make it memorable. Make it inviting to look at. Make it fun to read.", author: "Leo Burnett" },
    { id: 50, quote: "Keep going. Be all in.", author: "Bryan Hutchinson" }
  ];

  const i = Math.floor(Math.random() * quotes.length);
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  res.status(200).json(quotes[i]);
}
